# Generated by Django 4.2.2 on 2023-06-15 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skillmodel",
            name="price",
        ),
        migrations.AlterField(
            model_name="reviewmodel",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
