# Generated by Django 4.2.2 on 2023-06-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DayModel",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Lesson", "Lesson"),
                            ("Practice", "Practice"),
                            ("Rest", "Rest"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name="ReviewModel",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("user", models.CharField(max_length=50)),
                ("content", models.TextField(max_length=1000)),
                ("rating", models.IntegerField()),
                ("posted_day", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SkillModel",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("icon", models.ImageField(upload_to="")),
                ("creator", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=500)),
                ("price", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Normal", "Normal"),
                            ("Verified", "Verified"),
                            ("Premium", "Premium"),
                        ],
                        default="Normal",
                        max_length=10,
                    ),
                ),
                ("downloads", models.IntegerField()),
                (
                    "published_status",
                    models.CharField(
                        choices=[("Draft", "Draft"), ("Published", "Published")],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
